name: Sedimentology
main: org.foo_projects.sofar.Sedimentology.Sedimentology
version: 10
softdepend: [Factions, Towny, WorldGuard, Residence]
commands:
    sedimentology:
        aliases: sed
        description: Display help for the sedimentology plugin
        usage: /sedimentology ...
        permission: sedimentology
        permission-message: You do not have sufficient privileges to do that!
permissions:
    sedimentology:
        description: Gives access to the sedimentology command
        default: op
