name: Sedimentology
main: org.foo_projects.sofar.Sedimentology.Sedimentology
version: 9
softdepend: [Factions, Towny, WorldGuard]
commands:
    sedimentology:
        aliases: sed
        description: Display help for the sedimentology plugin
        usage: /sedimentology ...
        permission: sedimentology
        permission-message: You do not have sufficient privileges to do that!
